/* 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력하는 SQL문을 작성해주세요.
   결과는 카테고리명을 기준으로 오름차순 정렬해주세요. */
   
-- mysql
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A, BOOK_SALES B
WHERE A.BOOK_ID = B.BOOK_ID
  AND DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;

-- Oracle
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A, BOOK_SALES B
WHERE A.BOOK_ID = B.BOOK_ID
  AND TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;
